networks:
  cuaderno-network:

services:
  eureka-server:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-discovery-service
    ports:
      - "8761:8761"


  config-server:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - spring.cloud.config.server.native.search-locations=file:/config-repo/
    volumes:
        - ./config-repo:/config-repo


  mariadb:
    networks:
      - cuaderno-network
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=2203
      - MYSQL_DATABASE=cuaderno_db
    volumes:
      - mariadb_data:/var/lib/mysql

  gateway-service:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-gateway-service
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - mariadb
      - task-service
      - auth-service
      - notification-service

  task-service:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-task-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server
      - mariadb

  board-service:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-board-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server
      - mariadb


  auth-service:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
      - mariadb


  notification-service:
    networks:
      - cuaderno-network
    build:
      context: ./cuaderno-notification-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server
      - mariadb


volumes:
  mariadb_data: